wordpress:
  image:
    repository: wordpress
    tag: latest
  persistence:
    enabled: true
  service:
    type: LoadBalancer

mysql:
  image:
    repository: mysql
    tag: 5.7
  mysqlRootPassword: test1234
  mysqlUser: alireza
  mysqlPassword: test1234
  mysqlDatabase: rayankar
