apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-chart.fullname" . }}
spec:
  selector:
    app: {{ include "wordpress-chart.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: {{ .Values.wordpress.service.type }}
